$schema: "http://json-schema.org/draft-06/schema#"
description: schema for config parameters

type: object
properties:
  subseq:
    type: object
    default:
      subseq_min_len: 300 # Minimum length of subsequence to be extracted from the reference
      hmm_from: 78
      hmm_to: 202
      asv_seq: "AATAAATAACATAAGATTTTGATTATTACCCCCTTCTTTATCTTTACTATTAATTAGAAGAATAGTTGAAACTGGAACAGGTACCGGATGAACTGTTTACCCACCATTATCTTCTATTATTGCTCATACAGGATCATCAGTAGATTTTTCAATTTTTTCTTTACATATTGCAGGAATTTCATCTATTTTAGGAGCTATTAATTTTATTTCAACTATATTAAATATAAAAATCAAATTTTTAAAATTTGATCAAATTTCATTATTTATTTGATCAATTTTAATTACAACTGTATTATTACTTTTATCATTACCTGTATTAGCAGGAGCAATTACTATACTATTAACAGATCGAAATTTAAATACATCATTTTTTGATCCTATAGGAGGAGGAGATCCAATTCTTTATCAACATTTATTT"
    properties:
      subseq_min_len:
        type: integer
        description: Minimum length of subsequence to keep
        default: 300
      hmm_from:
        type: integer
        description: Start position of the gene amplicon region on the HMM
        default: 78
      hmm_to:
        type: integer
        description: End position of the gene amplicon region on the HMM
        default: 202
      asv_seq:
        type: string
        description: Example ASV sequence to use in alignment
        default: "AATAAATAACATAAGATTTTGATTATTACCCCCTTCTTTATCTTTACTATTAATTAGAAGAATAGTTGAAACTGGAACAGGTACCGGATGAACTGTTTACCCACCATTATCTTCTATTATTGCTCATACAGGATCATCAGTAGATTTTTCAATTTTTTCTTTACATATTGCAGGAATTTCATCTATTTTAGGAGCTATTAATTTTATTTCAACTATATTAAATATAAAAATCAAATTTTTAAAATTTGATCAAATTTCATTATTTATTTGATCAATTTTAATTACAACTGTATTATTACTTTTATCATTACCTGTATTAGCAGGAGCAATTACTATACTATTAACAGATCGAAATTTAAATACATCATTTTTTGATCCTATAGGAGGAGGAGATCCAATTCTTTATCAACATTTATTT"
  testing:
    type: object
    default:
      nrows: 0
    nrows:
      type: integer
      description: For testing purposes, set number of rows to load with pandas
      default: 0
  primers:
    type: object
    default:
      forward: ["CCHGAYATRGCHTTYCCHCG"]
      reverse: ["CDGGRTGNCCRAARAAYCA"]
    forward:
      type: array
      description: Forward primer sequence(s)
      default: ["CCHGAYATRGCHTTYCCHCG"]
      items:
        type: string
    reverse:
      type: array
      description: Reverse primer sequence(s)
      default: ["CDGGRTGNCCRAARAAYCA"]
      items:
        type: string

  database:
    type: object
    default:
      pid: 1.0
      bold.zip: "https://hosted-datasets.gbif.org/ibol/ibol_2022_01_17.zip"
      backbone.zip: "https://hosted-datasets.gbif.org/datasets/backbone/2022-11-23/backbone.zip"
      gene:
        - COI-5P
      taxa: []
      rank: "phylum"
      ranks:
        - kingdom
        - phylum
        - class
        - order
        - family
        - genus
        - species
    properties:
      pid:
        type: number
        description: Id threshold for clustering database with vsearch
        default: 1.0
        max: 1.0
        min: 0.0
      bold.zip:
        type: string
        default: "https://hosted-datasets.gbif.org/ibol/ibol_2022_01_17.zip"
        description: URL to zipfile with database sequences + info
      backbone.zip:
        type: string
        default: "https://hosted-datasets.gbif.org/datasets/backbone/2022-11-23/backbone.zip"
        description: URL to GBIF taxonomy backbone
      gene:
        type: array
        description: Genes of interest to extract from database
        default:
          - "COI-5P"
        items:
          type: string
      taxa:
        type: array
        description: Taxa of interest to extract from database
        default: []
        items:
          type: string
      rank:
        type: string
        description: Rank at which to filter using the taxa above
        default: "phylum"
      ranks:
        type: array
        description: Ranks to include in taxonomic info
        default: ["kingdom", "phylum", "class", "order", "family", "genus", "species"]
        items:
          type: string
          enum: ["kingdom", "phylum", "class", "order", "family", "genus", "species"]
  sintax:
    type: object
    default:
      ranks: ["domain", "kingdom", "phylum", "class", "order", "family", "genus", "species"]
      replace_ranks: ["kingdom=domain", "phylum=kingdom", "class=phylum", "order=class", "family=order", "genus=family", "species=genus", "bold_id=species"]
    ranks:
      type: array
      description: Ranks to include in sintax formatted fasta
      default:
        - "domain"
        - "kingdom"
        - "phylum"
        - "class"
        - "order"
        - "family"
        - "genus"
        - "species"
    replace_ranks:
      type: array
      description: Replacement keys for ranks
      default:
        - "kingdom=domain"
        - "phylum=kingdom"
        - "class=phylum"
        - "order=class"
        - "family=order"
        - "genus=family"
        - "species=genus"
        - "bold_id=species"